package com.github.gbandszxc.obt.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// ---------------------------------------------------------------------------
// 预置调色盘目录：6 套 Material 3 配色，每套浅/深两个完整 scheme。
// - 首位「青瓷绿」为品牌默认，浅/深色值与改造前完全一致（默认视觉不变）；
// - 其余五套按 M3 tonal 角色（primary=40/80、container=90/30、on*=10/90 等）手工调配，
//   正文类对比度（onSurface/onSurfaceVariant/on*Container vs 对应底色）均按 WCAG ≥4.5:1 校验；
// - error 系沿用 Material 基准错误色，各套一致；
// - 未显式赋值的 roles 由 lightColorScheme()/darkColorScheme() 默认参数兜底（本文件已全部覆盖）。
// ---------------------------------------------------------------------------

/** 单套调色盘：[id] 持久化于设置，[label]/[preview] 供设置界面展示色板。 */
data class ThemePalette(
    val id: String,
    val label: String,
    val light: ColorScheme,
    val dark: ColorScheme,
    val preview: Color,
)

/**
 * 调色盘目录：列表顺序即设置界面展示顺序，首位为默认（青瓷绿）。
 * 用 lazy 延迟到首次访问初始化，规避 Kotlin 顶层属性声明顺序对下方 scheme 常量的前向引用。
 */
val ThemePalettes: List<ThemePalette> by lazy {
    listOf(
        ThemePalette(
            id = "celadon",
            label = "青瓷绿",
            light = CeladonLight,
            dark = CeladonDark,
            preview = CeladonLight.primary,
        ),
        ThemePalette(
            id = "indigo",
            label = "靛蓝",
            light = IndigoLight,
            dark = IndigoDark,
            preview = IndigoLight.primary,
        ),
        ThemePalette(
            id = "amber",
            label = "琥珀暖橙",
            light = AmberLight,
            dark = AmberDark,
            preview = AmberLight.primary,
        ),
        ThemePalette(
            id = "rose",
            label = "玫瑰红",
            light = RoseLight,
            dark = RoseDark,
            preview = RoseLight.primary,
        ),
        ThemePalette(
            id = "forest",
            label = "森林绿",
            light = ForestLight,
            dark = ForestDark,
            preview = ForestLight.primary,
        ),
        ThemePalette(
            id = "cerulean",
            label = "天青蓝",
            light = CeruleanLight,
            dark = CeruleanDark,
            preview = CeruleanLight.primary,
        ),
    )
}

// ---------------------------------------------------------------------------
// 青瓷绿（品牌默认，保留改造前色值）
// ---------------------------------------------------------------------------

/** 青瓷绿·浅色：中性微绿表面 + 青瓷绿强调色。 */
val CeladonLight: ColorScheme = lightColorScheme(
    primary = Color(0xFF1F6B58),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFA7F3DB),
    onPrimaryContainer = Color(0xFF00201A),
    secondary = Color(0xFF4A635B),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCCE9DE),
    onSecondaryContainer = Color(0xFF072019),
    tertiary = Color(0xFF41636E),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFC5E8F5),
    onTertiaryContainer = Color(0xFF001F28),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFF5FBF7),
    onBackground = Color(0xFF171D1A),
    surface = Color(0xFFF5FBF7),
    onSurface = Color(0xFF171D1A),
    surfaceVariant = Color(0xFFDBE5E0),
    onSurfaceVariant = Color(0xFF3F4945),
    outline = Color(0xFF6F7975),
    outlineVariant = Color(0xFFBEC9C4),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF2B322F),
    inverseOnSurface = Color(0xFFECF2EE),
    inversePrimary = Color(0xFF8BD7BE),
    surfaceDim = Color(0xFFD5DBD7),
    surfaceBright = Color(0xFFF5FBF7),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFEFF5F1),
    surfaceContainer = Color(0xFFE9EFEB),
    surfaceContainerHigh = Color(0xFFE4E9E6),
    surfaceContainerHighest = Color(0xFFDEE4E0),
)

/** 青瓷绿·深色。 */
val CeladonDark: ColorScheme = darkColorScheme(
    primary = Color(0xFF86D8C1),
    onPrimary = Color(0xFF00382D),
    primaryContainer = Color(0xFF005144),
    onPrimaryContainer = Color(0xFFA2F3DB),
    secondary = Color(0xFFB1CCC2),
    onSecondary = Color(0xFF1C352E),
    secondaryContainer = Color(0xFF334B44),
    onSecondaryContainer = Color(0xFFCCE9DE),
    tertiary = Color(0xFFA9CCD9),
    onTertiary = Color(0xFF0E343E),
    tertiaryContainer = Color(0xFF2A4B55),
    onTertiaryContainer = Color(0xFFC5E8F5),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF0F1512),
    onBackground = Color(0xFFDEE4E0),
    surface = Color(0xFF0F1512),
    onSurface = Color(0xFFDEE4E0),
    surfaceVariant = Color(0xFF3F4945),
    onSurfaceVariant = Color(0xFFBEC9C4),
    outline = Color(0xFF89938E),
    outlineVariant = Color(0xFF3F4945),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFDEE4E0),
    inverseOnSurface = Color(0xFF2B322F),
    inversePrimary = Color(0xFF1F6B58),
    surfaceDim = Color(0xFF0F1512),
    surfaceBright = Color(0xFF343B37),
    surfaceContainerLowest = Color(0xFF0A100D),
    surfaceContainerLow = Color(0xFF171D1A),
    surfaceContainer = Color(0xFF1B211E),
    surfaceContainerHigh = Color(0xFF252B28),
    surfaceContainerHighest = Color(0xFF303634),
)

// ---------------------------------------------------------------------------
// 靛蓝：沉稳的蓝紫之间偏蓝，避免俗气紫色，tertiary 用青色拉开层次
// ---------------------------------------------------------------------------

/** 靛蓝·浅色。 */
val IndigoLight: ColorScheme = lightColorScheme(
    primary = Color(0xFF3E4FC0),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFDDE0FF),
    onPrimaryContainer = Color(0xFF000F5C),
    secondary = Color(0xFF5A5D72),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFDEE1FA),
    onSecondaryContainer = Color(0xFF171B2C),
    tertiary = Color(0xFF00696C),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF9CF1F3),
    onTertiaryContainer = Color(0xFF002021),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFF8F9FF),
    onBackground = Color(0xFF1A1B21),
    surface = Color(0xFFF8F9FF),
    onSurface = Color(0xFF1A1B21),
    surfaceVariant = Color(0xFFE2E2EC),
    onSurfaceVariant = Color(0xFF45464F),
    outline = Color(0xFF757680),
    outlineVariant = Color(0xFFC5C6D0),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF2F303A),
    inverseOnSurface = Color(0xFFF1F0F9),
    inversePrimary = Color(0xFFBAC2FF),
    surfaceDim = Color(0xFFD9DAE3),
    surfaceBright = Color(0xFFF8F9FF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF2F3FC),
    surfaceContainer = Color(0xFFECECF6),
    surfaceContainerHigh = Color(0xFFE6E7F0),
    surfaceContainerHighest = Color(0xFFE2E2EC),
)

/** 靛蓝·深色。 */
val IndigoDark: ColorScheme = darkColorScheme(
    primary = Color(0xFFBAC2FF),
    onPrimary = Color(0xFF131C68),
    primaryContainer = Color(0xFF2C3AA5),
    onPrimaryContainer = Color(0xFFDDE0FF),
    secondary = Color(0xFFC3C5DD),
    onSecondary = Color(0xFF2C2F42),
    secondaryContainer = Color(0xFF424659),
    onSecondaryContainer = Color(0xFFDEE1FA),
    tertiary = Color(0xFF80D4E6),
    onTertiary = Color(0xFF003639),
    tertiaryContainer = Color(0xFF004F53),
    onTertiaryContainer = Color(0xFF9CF1F3),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF11131A),
    onBackground = Color(0xFFE2E1EC),
    surface = Color(0xFF11131A),
    onSurface = Color(0xFFE2E1EC),
    surfaceVariant = Color(0xFF45464F),
    onSurfaceVariant = Color(0xFFC5C6D0),
    outline = Color(0xFF8F909A),
    outlineVariant = Color(0xFF45464F),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE2E1EC),
    inverseOnSurface = Color(0xFF2F303A),
    inversePrimary = Color(0xFF3E4FC0),
    surfaceDim = Color(0xFF11131A),
    surfaceBright = Color(0xFF3B3C45),
    surfaceContainerLowest = Color(0xFF0C0E14),
    surfaceContainerLow = Color(0xFF191A23),
    surfaceContainer = Color(0xFF1D1F27),
    surfaceContainerHigh = Color(0xFF272932),
    surfaceContainerHighest = Color(0xFF32333D),
)

// ---------------------------------------------------------------------------
// 琥珀暖橙：陶土橙 + 暖褐中性色，tertiary 用湖青对比提亮
// ---------------------------------------------------------------------------

/** 琥珀暖橙·浅色。 */
val AmberLight: ColorScheme = lightColorScheme(
    primary = Color(0xFF8B5000),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDCC2),
    onPrimaryContainer = Color(0xFF2E1500),
    secondary = Color(0xFF755845),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDBBE),
    onSecondaryContainer = Color(0xFF2A160A),
    tertiary = Color(0xFF006874),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFB4ECFF),
    onTertiaryContainer = Color(0xFF001F24),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFF8F5),
    onBackground = Color(0xFF201A17),
    surface = Color(0xFFFFF8F5),
    onSurface = Color(0xFF201A17),
    surfaceVariant = Color(0xFFF4DFD4),
    onSurfaceVariant = Color(0xFF52443C),
    outline = Color(0xFF85736B),
    outlineVariant = Color(0xFFD7C3B9),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF362F2B),
    inverseOnSurface = Color(0xFFFBEEE9),
    inversePrimary = Color(0xFFFFB77C),
    surfaceDim = Color(0xFFE4D9D3),
    surfaceBright = Color(0xFFFFF8F5),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFDF2EC),
    surfaceContainer = Color(0xFFF7ECE5),
    surfaceContainerHigh = Color(0xFFF1E6E0),
    surfaceContainerHighest = Color(0xFFECE0DA),
)

/** 琥珀暖橙·深色。 */
val AmberDark: ColorScheme = darkColorScheme(
    primary = Color(0xFFFFB77C),
    onPrimary = Color(0xFF4C2800),
    primaryContainer = Color(0xFF6E3A00),
    onPrimaryContainer = Color(0xFFFFDCC2),
    secondary = Color(0xFFE3BFA9),
    onSecondary = Color(0xFF432B1B),
    secondaryContainer = Color(0xFF5C4130),
    onSecondaryContainer = Color(0xFFFFDBBE),
    tertiary = Color(0xFF82D3E9),
    onTertiary = Color(0xFF00363F),
    tertiaryContainer = Color(0xFF004E58),
    onTertiaryContainer = Color(0xFFB4ECFF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1A120D),
    onBackground = Color(0xFFECE0DA),
    surface = Color(0xFF1A120D),
    onSurface = Color(0xFFECE0DA),
    surfaceVariant = Color(0xFF52443C),
    onSurfaceVariant = Color(0xFFD7C3B9),
    outline = Color(0xFF9F8D84),
    outlineVariant = Color(0xFF52443C),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFECE0DA),
    inverseOnSurface = Color(0xFF362F2B),
    inversePrimary = Color(0xFF8B5000),
    surfaceDim = Color(0xFF1A120D),
    surfaceBright = Color(0xFF413933),
    surfaceContainerLowest = Color(0xFF140C08),
    surfaceContainerLow = Color(0xFF221A15),
    surfaceContainer = Color(0xFF261E19),
    surfaceContainerHigh = Color(0xFF312823),
    surfaceContainerHighest = Color(0xFF3C332E),
)

// ---------------------------------------------------------------------------
// 玫瑰红：正红偏粉的玫瑰主色，tertiary 用湖青互补，避免橙红糊成一片
// ---------------------------------------------------------------------------

/** 玫瑰红·浅色。 */
val RoseLight: ColorScheme = lightColorScheme(
    primary = Color(0xFF9C4145),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDAD9),
    onPrimaryContainer = Color(0xFF410008),
    secondary = Color(0xFF775657),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDADA),
    onSecondaryContainer = Color(0xFF2C1516),
    tertiary = Color(0xFF33696D),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFB5ECEF),
    onTertiaryContainer = Color(0xFF002022),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFF8F7),
    onBackground = Color(0xFF201A1B),
    surface = Color(0xFFFFF8F7),
    onSurface = Color(0xFF201A1B),
    surfaceVariant = Color(0xFFF4DDDD),
    onSurfaceVariant = Color(0xFF534343),
    outline = Color(0xFF867372),
    outlineVariant = Color(0xFFD9C1C1),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF352F2F),
    inverseOnSurface = Color(0xFFFBEDED),
    inversePrimary = Color(0xFFFFB3B4),
    surfaceDim = Color(0xFFE4D7D7),
    surfaceBright = Color(0xFFFFF8F7),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFDF1F0),
    surfaceContainer = Color(0xFFF8EAEA),
    surfaceContainerHigh = Color(0xFFF2E4E4),
    surfaceContainerHighest = Color(0xFFECDFDE),
)

/** 玫瑰红·深色。 */
val RoseDark: ColorScheme = darkColorScheme(
    primary = Color(0xFFFFB3B4),
    onPrimary = Color(0xFF650016),
    primaryContainer = Color(0xFF7E2A2E),
    onPrimaryContainer = Color(0xFFFFDAD9),
    secondary = Color(0xFFE6BDBC),
    onSecondary = Color(0xFF442928),
    secondaryContainer = Color(0xFF5D3F3E),
    onSecondaryContainer = Color(0xFFFFDADA),
    tertiary = Color(0xFF9BD0D0),
    onTertiary = Color(0xFF003735),
    tertiaryContainer = Color(0xFF204F4E),
    onTertiaryContainer = Color(0xFFB5ECEF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1A1111),
    onBackground = Color(0xFFECDFDE),
    surface = Color(0xFF1A1111),
    onSurface = Color(0xFFECDFDE),
    surfaceVariant = Color(0xFF534343),
    onSurfaceVariant = Color(0xFFD9C1C1),
    outline = Color(0xFF9F8C8B),
    outlineVariant = Color(0xFF534343),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFECDFDE),
    inverseOnSurface = Color(0xFF352F2F),
    inversePrimary = Color(0xFF9C4145),
    surfaceDim = Color(0xFF1A1111),
    surfaceBright = Color(0xFF423939),
    surfaceContainerLowest = Color(0xFF140C0C),
    surfaceContainerLow = Color(0xFF221919),
    surfaceContainer = Color(0xFF261D1D),
    surfaceContainerHigh = Color(0xFF312827),
    surfaceContainerHighest = Color(0xFF3C3333),
)

// ---------------------------------------------------------------------------
// 森林绿：低饱和深绿 + 灰绿中性色，tertiary 用青绿呼应自然系
// ---------------------------------------------------------------------------

/** 森林绿·浅色。 */
val ForestLight: ColorScheme = lightColorScheme(
    primary = Color(0xFF38693C),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFB1F1AC),
    onPrimaryContainer = Color(0xFF002204),
    secondary = Color(0xFF53634B),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD7E8C8),
    onSecondaryContainer = Color(0xFF121E0E),
    tertiary = Color(0xFF00696D),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF9DF0F1),
    onTertiaryContainer = Color(0xFF002021),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFF8FBF2),
    onBackground = Color(0xFF191D17),
    surface = Color(0xFFF8FBF2),
    onSurface = Color(0xFF191D17),
    surfaceVariant = Color(0xFFDEE5D4),
    onSurfaceVariant = Color(0xFF424940),
    outline = Color(0xFF72796F),
    outlineVariant = Color(0xFFC1C9BD),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF2E322A),
    inverseOnSurface = Color(0xFFEDF2E5),
    inversePrimary = Color(0xFF96D791),
    surfaceDim = Color(0xFFD7DBD0),
    surfaceBright = Color(0xFFF8FBF2),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF2F5EC),
    surfaceContainer = Color(0xFFECEFE6),
    surfaceContainerHigh = Color(0xFFE6EAE1),
    surfaceContainerHighest = Color(0xFFE0E4DB),
)

/** 森林绿·深色。 */
val ForestDark: ColorScheme = darkColorScheme(
    primary = Color(0xFF96D791),
    onPrimary = Color(0xFF0B390F),
    primaryContainer = Color(0xFF215124),
    onPrimaryContainer = Color(0xFFB1F1AC),
    secondary = Color(0xFFBBCAAF),
    onSecondary = Color(0xFF263421),
    secondaryContainer = Color(0xFF3C4B36),
    onSecondaryContainer = Color(0xFFD7E8C8),
    tertiary = Color(0xFF80D3D5),
    onTertiary = Color(0xFF003736),
    tertiaryContainer = Color(0xFF004F4F),
    onTertiaryContainer = Color(0xFF9DF0F1),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF10140F),
    onBackground = Color(0xFFE0E4DB),
    surface = Color(0xFF10140F),
    onSurface = Color(0xFFE0E4DB),
    surfaceVariant = Color(0xFF424940),
    onSurfaceVariant = Color(0xFFC1C9BD),
    outline = Color(0xFF8B9388),
    outlineVariant = Color(0xFF424940),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE0E4DB),
    inverseOnSurface = Color(0xFF2E322A),
    inversePrimary = Color(0xFF38693C),
    surfaceDim = Color(0xFF10140F),
    surfaceBright = Color(0xFF363A34),
    surfaceContainerLowest = Color(0xFF0B0F0A),
    surfaceContainerLow = Color(0xFF181D16),
    surfaceContainer = Color(0xFF1C211A),
    surfaceContainerHigh = Color(0xFF262B24),
    surfaceContainerHighest = Color(0xFF31362F),
)

// ---------------------------------------------------------------------------
// 天青蓝：晴空青蓝 + 蓝灰中性色，tertiary 用青绿增添清新层次
// ---------------------------------------------------------------------------

/** 天青蓝·浅色。 */
val CeruleanLight: ColorScheme = lightColorScheme(
    primary = Color(0xFF00639B),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFCEE5FF),
    onPrimaryContainer = Color(0xFF001D34),
    secondary = Color(0xFF51606F),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD5E4F7),
    onSecondaryContainer = Color(0xFF0E1D2A),
    tertiary = Color(0xFF226C64),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFA9F0E0),
    onTertiaryContainer = Color(0xFF00201C),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFF7F9FE),
    onBackground = Color(0xFF191C20),
    surface = Color(0xFFF7F9FE),
    onSurface = Color(0xFF191C20),
    surfaceVariant = Color(0xFFDCE3EA),
    onSurfaceVariant = Color(0xFF41474D),
    outline = Color(0xFF72777E),
    outlineVariant = Color(0xFFC1C7CE),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF2D3135),
    inverseOnSurface = Color(0xFFEDF1F5),
    inversePrimary = Color(0xFF98CBFF),
    surfaceDim = Color(0xFFD7DAE0),
    surfaceBright = Color(0xFFF7F9FE),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF1F4F9),
    surfaceContainer = Color(0xFFEBEEF3),
    surfaceContainerHigh = Color(0xFFE5E8EE),
    surfaceContainerHighest = Color(0xFFDFE3E8),
)

/** 天青蓝·深色。 */
val CeruleanDark: ColorScheme = darkColorScheme(
    primary = Color(0xFF98CBFF),
    onPrimary = Color(0xFF003256),
    primaryContainer = Color(0xFF00497A),
    onPrimaryContainer = Color(0xFFCEE5FF),
    secondary = Color(0xFFB9C8DA),
    onSecondary = Color(0xFF233340),
    secondaryContainer = Color(0xFF3A4958),
    onSecondaryContainer = Color(0xFFD5E4F7),
    tertiary = Color(0xFF8CD1C5),
    onTertiary = Color(0xFF00382F),
    tertiaryContainer = Color(0xFF005145),
    onTertiaryContainer = Color(0xFFA9F0E0),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF101418),
    onBackground = Color(0xFFDFE3E8),
    surface = Color(0xFF101418),
    onSurface = Color(0xFFDFE3E8),
    surfaceVariant = Color(0xFF41474D),
    onSurfaceVariant = Color(0xFFC1C7CE),
    outline = Color(0xFF8B9198),
    outlineVariant = Color(0xFF41474D),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFDFE3E8),
    inverseOnSurface = Color(0xFF2D3135),
    inversePrimary = Color(0xFF00639B),
    surfaceDim = Color(0xFF101418),
    surfaceBright = Color(0xFF363A40),
    surfaceContainerLowest = Color(0xFF0B0E12),
    surfaceContainerLow = Color(0xFF181C20),
    surfaceContainer = Color(0xFF1C2024),
    surfaceContainerHigh = Color(0xFF262A2F),
    surfaceContainerHighest = Color(0xFF31353A),
)
